language: ruby
rvm:
- 2.3.0
branches:
  only: master
script: bundle exec rake build
cache: bundler
deploy:
  provider: s3
  access_key_id: AKIAIE35NTBL6WPXE2FA
  secret_access_key:
    secure: Mvlkzekgp7Cc/ywD5mIKwwd4NiNyYnuSx+b4Bs5gvAJO3sTbNC2XaT0XkMkAHHqG73ULlOQerkc9dODS7XEsYuV4vcEBaQqyUer203Vr64TwNtUwu1Fg4udtEqE4K2vBtdVoFmCGFs69uMUlG59s/Y58n0bkdw/7gqx/1w4f8+7ilFrv1Wy2txPeNE9rRA+wLFuIddLuVlAz4Jzus6pR1zN14pamTEjTnxZVwtZLVmtdZcsBGMEtvdN35V0qDC7F+LEb8HmeEhw2eYbvbzVQU8DWApcoFuBNiKPhSfp7cyeqkFyV+YVetjZWUcRNa/UThPUhutW4iTTkP+chBmCfpa62kXGQJjW/o6Dryr4BR0v8onSV3N2CgEdtQ1poyTcYMI700BfD6hMiAZGeOF943O1Gvfj4A4opOe7ad2tIgjMG2pxGOccaTDqqIwhUDtDKpf+RxbdF1VqnQjfB2s63xlUPsNvKB2EAGQ2rFxbcwLNiUKWpALuLOJgxuZXkTTBkdIYJXzakgXjmWz1F00hbSLC/PknjYaM8EwN4kTg7nFS/HU2uVI8ekSdrGC7An9pEygChd+ERHElMnH7ortnUb5y94PrDCPTkty1p7S/mtN6h0bx59LZvUvVBh46ZB/zwijkJCTp3fsCFFzT46vEM4eiT6z4r6kQcXbtvmipx7Lo=
  bucket: quandrax.com
  acl: bucket_owner_full_control
  on:
    repo: MiltonStanley/quandrax.com
